name: Git Actions CI/CD

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master


jobs:
  read_hello_file:
    runs-on: [self-hosted, Windows, X64, Osta_test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read hello.txt
        run: type hello.txt
        